config/routes.rb
Rails.application.routes.draw do
  resources :players

  root 'players#index'

end

app/models/player.rb
class Player < ActiveRecord::Base

  validates_numericality_of :wins, only_integer: true, greater_than_or_equal_to: 0
  validates_numericality_of :losses, only_integer: true, greater_than_or_equal_to: 0


  def mark_win
    self.update(wins: self.wins + 1)
  end

  def mark_loss
    self.update(losses: self.losses + 1)
  end

  def win_ratio
    return nil if total_games == 0

    wins / total_games.to_f
  end

  def total_games
    losses + wins
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index



    @players = Player.order(wins: :desc, losses: :asc)
  end

  # GET /players/1
  # GET /players/1.json
  def show
    respond_to :json
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to players_path(player_action: 'added', player_id: @player.id), notice: 'Player added.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.mark_win
        format.html { redirect_to players_path(player_action: 'win', player_id: @player.id) }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render players_path, alert: 'There was an error' }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    respond_to do |format|
      if @player.mark_loss
        format.html { redirect_to players_path(player_action: 'loss', player_id: @player.id) }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render players_path, alert: 'There was an error' }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:name, :wins, :losses)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper

  def player_class(player)
    return unless params[:player_id].to_i == player.id

    case params[:player_action]
    when 'added'
      'player--added'
    when 'win'
      'player--win'
    when 'loss'
      'player--loss'
    else
      nil
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Leaderboard</title>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
    <%= yield %>
</div>

</body>
</html>

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit 'Create', class: 'btn btn-md btn-success' %>
  </div>
<% end %>

app/views/players/index.html.erb
<p class="bg-failure"><%= alert %></p>

<h1>The Leader Board</h1>

<% if @players.blank? %>
    <h2>No players! Create one!</h2>
<% else %>
    <table class="table">
      <thead>
        <tr>
          <th>Rank</th>
          <th>Name</th>
          <th>Wins</th>
          <th>Losses</th>
          <th>Win Ratio</th>
          <th colspan="1"></th>
        </tr>
      </thead>

      <tbody>
        <% @players.each_with_index do |player, i| %>
          <tr class="player <%= player_class(player) %>">
            <td><%= i + 1 %></td>
            <td><%= player.name %></td>
            <td><%= player.wins %></td>
            <td><%= player.losses %></td>
            <td><%= number_with_precision(player.win_ratio, precision: 2) || '-' %></td>
            <td><%= link_to 'Win', player, method: :patch %> / <%= link_to 'Loss', player, method: :delete %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
<% end %>
<br>

<%= link_to 'New Player', new_player_path, class: 'btn btn-sm btn-primary' %>

app/views/players/new.html.erb
<h1>New Player</h1>

<%= render 'form' %>

<%= link_to 'Back', players_path %>